version: '3.5'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
            - "443:443"
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:fpm
        volumes:
            - .:/var/www/html
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
